// TODO: get these from env variables
// TODO: Get values of MUTUAL_AID_NEWSLETTER_SUBSCRIBE_LINK, MUTUAL_AID_SLACK_LINK, MUTUAL_AID_INSTAGRAM_LINK, MUTUAL_AID_FACEBOOK_LINK

const MUTUAL_AID_NEWSLETTER_SUBSCRIBE_LINK = "";
const MUTUAL_AID_SLACK_LINK = "";
const MUTUAL_AID_PHONE_NUMBER_COUNTRY_CODE = "+1",
      MUTUAL_AID_PHONE_NUMBER = "862-277-0747";
const MUTUAL_AID_EMAIL_ADDRESS_HELLO = "hello@chfgma.org";
const MUTUAL_AID_INSTAGRAM_LINK = "",
      MUTUAL_AID_FACEBOOK_LINK = "";

const config = {
    MUTUAL_AID_NEWSLETTER_SUBSCRIBE_LINK,
    MUTUAL_AID_SLACK_LINK,
    MUTUAL_AID_PHONE_NUMBER_COUNTRY_CODE,
    MUTUAL_AID_PHONE_NUMBER,
    MUTUAL_AID_EMAIL_ADDRESS_HELLO,
    MUTUAL_AID_INSTAGRAM_LINK,
    MUTUAL_AID_FACEBOOK_LINK,
}

export default config;