export const MUTUAL_AID_NYC_LINK = "https://mutualaid.nyc/",
    MUTUAL_AID_NEWSLETTER_SUBSCRIBE_LINK = "https://notion.us19.list-manage.com/subscribe?u=a2f7efb31fe0c09ee5856bacb&id=9db6a5352a",
    MUTUAL_AID_SLACK_LINK = "https://chfgmutualaid.slack.com/join/shared_invite/zt-dol9r5tu-Af~7Y5IIpCW17oOL~wBa1A#/",
    MUTUAL_AID_PHONE_NUMBER_COUNTRY_CODE = "+1",
    MUTUAL_AID_PHONE_NUMBER = "862-277-0747",
    MUTUAL_AID_EMAIL_ADDRESS_HELLO = "hello@chfgma.org",
    MUTUAL_AID_INSTAGRAM_LINK = "https://www.instagram.com/chfgaid/",
    MUTUAL_AID_FACEBOOK_LINK = "https://www.facebook.com/chfgaid/",
    MUTUAL_AID_AIRTABLE_LINK = "https://airtable.com/shrAwewkpHBHWyh5L/tbl4xknvSOLNB7bcI",
    MUTUAL_AID_INSTAGRAM_FRIDGE_LINK = "https://www.instagram.com/fgcommunityfridge/",
    IDGE_LOCATION_LINK = "https://www.google.com/maps/place/357+Myrtle+Ave,+Brooklyn,+NY+11205/@40.6847488,-73.97376,14z/export const !1s0x89c25bb7f11a68b7:0xca08dde714414b59!8m2!3d406934011!4d-73,9717401",
    COVID_TEXTING_HOTLINE = "692-692",
    MUTUAL_AID_REQUEST_FORM = "https://www.notion.so/Request-Form-59ad7cb64f904b1db0a0cad6c0171aac",
    MUTUAL_AID_WIKIPEDIA = "https://en.wikipedia.org/wiki/Mutual_aid_(organization_theory)#:~:text=In%20organization%20theory%2C%20mutual%20aid,another%20and%20changing%20political%20conditions.",
    MUTUAL_AID_NOTION_LINK = "https://www.notion.so/Clinton-Hill-Fort-Greene-Mutual-Aid-55c77817239345ee89eb5e8b13563dcd",
    IOBY_LINK = "https://ioby.org/project/clinton-hill-fort-greene-mutual-aid",
    DONORBOX_LINK = "https://donorbox.org/chfgma",
    HELP_NOW_NYC_LINK = "https://www1.nyc.gov/site/helpnownyc/index.page",
    NYC_WELL_LINK = "https://nycwell.cityofnewyork.us/en/",
    NOTIFY_NYC_LINK = "https://a858-nycnotify.nyc.gov/notifynyc",
    FLYER_PDF_LINK = "https://bit.ly/chfgflyer";